# Makefile for Programming Assignment 2 Test Programs
# Matthew Musselman (mmusselm)
# Felix Yeung (fyeung)
# Gabe Saluta (gsaluta)

test : prog_A.c prog_B.c prog_C.c prog_D.c
	gcc -o A prog_A.c
	gcc -o B prog_B.c
	gcc -o C prog_C.c
	gcc -o D prog_D.c

clean :
	rm -f A B C D
